// Together-inspired Mini Interpreter in JavaScript

// Helper to parse comments, variables, and basic syntax
function preprocess(code) {
  // Remove single-line comments ($$)
    code = code.replace(/\$\$.*$/gm, "");
      // Remove multi-line comments (>< ... ><)
        code = code.replace(/><[\s\S]*?><\s*/gm, "");
          return code;
          }

          // Basic Grouplet classes
          class ActionGrouplet {
            constructor(name) { this.name = name; this.lines = []; }
              run(context) {
                  for (const line of this.lines) {
                        if (/log\((.*)\)/.test(line)) {
                                const arg = RegExp.$1.trim();
                                        if (/^\[.*\]$/.test(arg)) {
                                                  // Variable
                                                            const varName = arg.slice(1, -1);
                                                                      console.log(context[varName]);
                                                                              } else {
                                                                                        // String literal
                                                                                                  console.log(eval(arg));
                                                                                                          }
                                                                                                                }
                                                                                                                      // Variable assignment inside Action
                                                                                                                            if (/^\[(.+)\]\s*=\s*["*]?(.*?)["*]?$/.test(line)) {
                                                                                                                                    const [, varName, varValue] = line.match(/^\[(.+)\]\s*=\s*["*]?(.*?)["*]?$/);
                                                                                                                                            context[varName] = varValue;
                                                                                                                                                  }
                                                                                                                                                      }
                                                                                                                                                        }
                                                                                                                                                        }

                                                                                                                                                        class StorageGrouplet {
                                                                                                                                                          constructor(name) { this.name = name; this.vars = {}; }
                                                                                                                                                            load(lines) {
                                                                                                                                                                for (const line of lines) {
                                                                                                                                                                      if (/^\[(.+)\]\s*=\s*["*]?(.*?)["*]?$/.test(line)) {
                                                                                                                                                                              const [, varName, varValue] = line.match(/^\[(.+)\]\s*=\s*["*]?(.*?)["*]?$/);
                                                                                                                                                                                      this.vars[varName] = varValue;
                                                                                                                                                                                            }
                                                                                                                                                                                                }
                                                                                                                                                                                                  }
                                                                                                                                                                                                  }

                                                                                                                                                                                                  class RunnerGrouplet {
                                                                                                                                                                                                    constructor(name) { this.name = name; this.actions = []; this.storages = []; }
                                                                                                                                                                                                      run() {
                                                                                                                                                                                                          const context = {};
                                                                                                                                                                                                              // Load storages first
                                                                                                                                                                                                                  for (const s of this.storages) Object.assign(context, s.vars);
                                                                                                                                                                                                                      // Run actions
                                                                                                                                                                                                                          for (const a of this.actions) a.run(context);
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                            // Parse Together-inspired code
                                                                                                                                                                                                                            function parseTogether(code) {
                                                                                                                                                                                                                              const grouplets = {};
                                                                                                                                                                                                                                const runnerGrouplets = [];
                                                                                                                                                                                                                                  let lines = code.split('\n').map(l => l.trim());
                                                                                                                                                                                                                                    let current = null;

                                                                                                                                                                                                                                      for (let i = 0; i < lines.length; i++) {
                                                                                                                                                                                                                                          let line = lines[i];

                                                                                                                                                                                                                                              // Grouplet definitions
                                                                                                                                                                                                                                                  if (/^(\w+)\s*=\s*Action\(Grouplet\)/i.test(line)) {
                                                                                                                                                                                                                                                        const name = line.match(/^(\w+)\s*=/)[1];
                                                                                                                                                                                                                                                              current = new ActionGrouplet(name);
                                                                                                                                                                                                                                                                    grouplets[name] = current;
                                                                                                                                                                                                                                                                          continue;
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                  if (/^(\w+)\s*=\s*Storage\(Grouplet\)/i.test(line)) {
                                                                                                                                                                                                                                                                                        const name = line.match(/^(\w+)\s*=/)[1];
                                                                                                                                                                                                                                                                                              current = new StorageGrouplet(name);
                                                                                                                                                                                                                                                                                                    grouplets[name] = current;
                                                                                                                                                                                                                                                                                                          continue;
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                  if (/^(\w+)\s*=\s*Runner\(Grouplet\)/i.test(line)) {
                                                                                                                                                                                                                                                                                                                        const name = line.match(/^(\w+)\s*=/)[1];
                                                                                                                                                                                                                                                                                                                              current = new RunnerGrouplet(name);
                                                                                                                                                                                                                                                                                                                                    grouplets[name] = current;
                                                                                                                                                                                                                                                                                                                                          runnerGrouplets.push(current);
                                                                                                                                                                                                                                                                                                                                                continue;
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                        // Process block
                                                                                                                                                                                                                                                                                                                                                            if (/^Process\((\w+)\)/.test(line)) {
                                                                                                                                                                                                                                                                                                                                                                  const name = line.match(/^Process\((\w+)\)/)[1];
                                                                                                                                                                                                                                                                                                                                                                        let block = [];
                                                                                                                                                                                                                                                                                                                                                                              i++; // Skip to next line
                                                                                                                                                                                                                                                                                                                                                                                    while (i < lines.length && !lines[i].startsWith('}')) block.push(lines[i++]);
                                                                                                                                                                                                                                                                                                                                                                                          if (grouplets[name] instanceof ActionGrouplet) grouplets[name].lines = block;
                                                                                                                                                                                                                                                                                                                                                                                                if (grouplets[name] instanceof StorageGrouplet) grouplets[name].load(block);
                                                                                                                                                                                                                                                                                                                                                                                                      continue;
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                              // Connect action/storage to runner
                                                                                                                                                                                                                                                                                                                                                                                                                  if (/^Connect\(([^,]+),\s*([^)]+)\)/.test(line)) {
                                                                                                                                                                                                                                                                                                                                                                                                                        const [, src, runner] = line.match(/^Connect\(([^,]+),\s*([^)]+)\)/);
                                                                                                                                                                                                                                                                                                                                                                                                                              if (grouplets[runner] instanceof RunnerGrouplet) {
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (grouplets[src] instanceof ActionGrouplet) grouplets[runner].actions.push(grouplets[src]);
                                                                                                                                                                                                                                                                                                                                                                                                                                              if (grouplets[src] instanceof StorageGrouplet) grouplets[runner].storages.push(grouplets[src]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Run all runners
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (const r of runnerGrouplets) r.run();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Example Together-like code
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const myCode = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    a = Action(Grouplet) $$ This is an action grouplet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Process(a) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ++action start
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [message] = "Hello World!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          log([message])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            --action end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            s = Storage(Grouplet)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Process(s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ++storage start
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [favoriteFood] = "Pizza"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  --storage end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  r = Runner(Grouplet)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Process(r) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ++run start
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      /run/ = <a, s>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        run(/run/)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          --run end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Connect(a, r)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Connect(s, r)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          parseTogether(preprocess(myCode));